config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  
  resources :users do
    resources :children
  end
  
  resources :program_enrollments do
    resources :reading_entries, only: [:create, :update]
  end
  
  resources :programs
  resources :collections
  resources :literary_works do
    member do
      get 'read', to: 'literary_works#read'
    end
  end
  resources :reading_entries

  revise_auth
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/views/shared/_breadcrumbs.html.erb
<% if breadcrumbs.any? %>
  <nav class="text-sm font-medium text-gray-500 mb-4" aria-label="Breadcrumb">
    <ol class="list-none p-0 inline-flex">
      <li class="flex items-center">
        <%= link_to "Home", root_path, class: "hover:text-gray-600 dark:text-slate-400" %>
      </li>
      <% breadcrumbs.each_with_index do |crumb, index| %>
        <li class="flex items-center">
          <svg class="fill-current w-3 h-3 mx-3" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512">
            <path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z"/>
          </svg>
          <% if index == breadcrumbs.size - 1 %>
            <span class="text-gray-600 dark:text-slate-400"><%= crumb.name %></span>
          <% else %>
            <%= link_to crumb.name, crumb.path, class: "hover:text-gray-600 dark:text-slate-400" %>
          <% end %>
        </li>
      <% end %>
    </ol>
  </nav>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="<%= flash_class(type) %> px-4 py-3 rounded-lg shadow-md mb-4" role="alert">
    <div class="flex items-center">
      <div class="flex-shrink-0">
        <%= flash_icon(type) %>
      </div>
      <div class="ml-3">
        <p class="text-sm font-medium"><%= message %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-gray-100 dark:bg-slate-800 mt-auto">
  <div class="container mx-auto px-4 py-8">
    <div class="flex flex-wrap justify-between">
      <div class="w-full md:w-1/3 mb-6 md:mb-0 sm:px-4">
        <h3 class="text-lg font-semibold mb-2 dark:text-white">About Us</h3>
        <p class="text-gray-600 dark:text-slate-400">Read the Junior Classics helps parents and educators introduce children to classic literature in a structured, age-appropriate manner.</p>
      </div>
      <div class="w-full md:w-1/3 mb-6 md:mb-0 sm:px-4">
        <h3 class="text-lg font-semibold mb-2 dark:text-white">Quick Links</h3>
        <ul class="text-gray-600 dark:text-slate-400">
          <li><%= link_to "Home", root_path, class: "hover:text-primary-500 hover:dark:text-slate-500" %></li>
          <li><%= link_to "Programs", programs_path, class: "hover:text-primary-500 hover:dark:text-slate-500" %></li>
          <li><%= link_to "Literary Works", literary_works_path, class: "hover:text-primary-500 hover:dark:text-slate-500" %></li>
          <li><%= link_to "Collections", collections_path, class: "hover:text-primary-500 hover:dark:text-slate-500" %></li>
        </ul>
      </div>
      <div class="w-full md:w-1/3 sm:px-4">
        <h3 class="text-lg font-semibold mb-2 dark:text-white">Contact Us</h3>
        <!-- <p class="text-gray-600 dark:text-slate-400">Email: info@readjuniorclassics.com</p> -->
        <iframe src="https://ghbtns.com/github-btn.html?user=bmbliss&repo=read-junior-classics&type=star&count=true&size=large" frameborder="0" scrolling="0" width="170" height="30" title="GitHub"></iframe>
      </div>
    </div>
    <div class="mt-8 text-center text-gray-500 dark:text-slate-500">
      <p>&copy; <%= Time.current.year %> Read the Junior Classics. All rights reserved.</p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-primary-500 text-white" data-controller="mobile-menu">
  <div class="container mx-auto px-4 py-4">
    <div class="flex justify-between items-center">
      <%= link_to root_path, class: "text-2xl font-bold flex items-center" do %>
        <%= image_tag "medieval.png", alt: "Medieval Icon", class: "w-8 h-8 mr-2" %>
        Read the Junior Classics
      <% end %>
      <nav class="hidden md:block">
        <ul class="flex space-x-4">
          <%= link_to "Home", root_path, class: "hover:text-primary-200" %>
          <%= link_to "Programs", programs_path, class: "hover:text-primary-200" %>
          <%= link_to "Literary Works", literary_works_path, class: "hover:text-primary-200" %>
          <%= link_to "Collections", collections_path, class: "hover:text-primary-200" %>
          <% if user_signed_in? %>
            <%= link_to "My Children", user_children_path(current_user), class: "hover:text-primary-200" %>
            <%= button_to "Log Out", logout_path, method: :delete, class: "hover:text-primary-200" %>
          <% else %>
            <%= link_to "Log In", login_path, class: "hover:text-primary-200" %>
            <%= link_to "Sign Up", sign_up_path, class: "hover:text-primary-200" %>
          <% end %>
          <div class="flex items-center">|</div>
          <div class="flex items-center">
            <input type="checkbox" id="theme-toggle" class="hidden" data-theme-target="toggle" data-action="change->theme#toggle">
            <label for="theme-toggle" class="flex items-center cursor-pointer">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 hidden dark:block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
              </svg>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 block dark:hidden" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
            </svg>
            </label>
          </div>
        </ul>
      </nav>
      <button class="md:hidden" data-action="click->mobile-menu#toggle">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
      </button>
    </div>
    <div class="md:hidden mt-4 hidden" data-mobile-menu-target="menu">
      <nav>
        <ul class="flex flex-col space-y-2">
          <%= link_to "Home", root_path, class: "hover:text-primary-200" %>
          <%= link_to "Programs", programs_path, class: "hover:text-primary-200" %>
          <%= link_to "Literary Works", literary_works_path, class: "hover:text-primary-200" %>
          <%= link_to "Collections", collections_path, class: "hover:text-primary-200" %>
          <% if user_signed_in? %>
            <%= link_to "My Children", user_children_path(current_user), class: "hover:text-primary-200" %>
            <%= button_to "Log Out", logout_path, method: :delete, class: "hover:text-primary-200 text-left w-full" %>
          <% else %>
            <%= link_to "Log In", login_path, class: "hover:text-primary-200" %>
            <%= link_to "Sign Up", sign_up_path, class: "hover:text-primary-200" %>
          <% end %>

          <hr class="w-1/3 my-2" />
          <div class="flex items-center">
            <input type="checkbox" id="theme-toggle" class="hidden" data-theme-target="toggle" data-action="change->theme#toggle">
            <label for="theme-toggle" class="flex items-center cursor-pointer">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 hidden dark:block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
              </svg>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 block dark:hidden" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
            </svg>
            </label>
          </div>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/shared/_star_rating_input.html.erb
<div class="flex items-center gap-1" data-controller="star-rating">
  <% 5.times do |i| %>
    <%= button_tag type: "button",
        class: "text-2xl focus:outline-none transition-colors duration-150",
        data: {
          action: "star-rating#rate mouseover->star-rating#hover mouseout->star-rating#resetHover",
          "star-rating-target": "star",
          "star-rating-index-value": i + 1,
          "star-rating-current-value": current_rating
        } do %>
      <span class="<%= i < current_rating ? 'text-yellow-400' : 'text-gray-300' %> hover:text-yellow-300">★</span>
    <% end %>
  <% end %>
  <%= hidden_field_tag field_name, current_rating, data: { "star-rating-target": "input" } %>
</div> 